# TODO: order everything in this file by preference and alphabetically
tap 'buo/cask-upgrade'
# tap 'git-friendly/homebrew-git-friendly'
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

# brew 'bitwarden-cli'
brew 'bat'
brew 'bash'
# brew 'direnv'
brew 'exa'
brew 'fx'
brew 'git'
# brew 'git-extras'
# brew 'git-friendly'
# brew 'glances' # TODO: rename top alias to glances
# brew 'glow'
# brew 'httpie'
# brew 'mkcert'
# brew 'prettyping'
brew 'starship'
# brew 'thefuck'
# brew 'tldr'
brew 'zsh'

# cask 'visual-studio-code'

cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-fira-mono'
cask 'font-fira-sans'
cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-open-dyslexic'
