#!/bin/bash

# A credential helper for git to retrieve usernames and passwords from Bitwarden.
# For general usage, see https://git-scm.com/docs/gitcredentials.
# Here's a quick version:
# 1. Put this somewhere in your path.
# 2. git config --global credential.helper bitwarden

# TODO: completely rewrite... using zsh? js? py? or other...

declare -a params

# This means alfred plugin for bitwarden needs to be installed
# https://github.com/blacs30/bitwarden-alfred-workflow
TOKEN=$(security find-generic-password -a token -s "com.lisowski-development.alfred.bitwarden" -w)

if [ "x$1" == "x-l" ]; then
	shift
	bwuser=$1
	shift
fi

# echo "step 1"

if [ "x$1" == "xget" ]; then
	read line

	while [ -n "$line" ]; do
		key=${line%%=*}
		value=${line#*=}
		params[$key]=$value
		read line
	done

  	# echo "step 2 ${params}"

  	# if [ "x${params['protocol']}" != "xhttps" ]; then
	#   	echo "exit 1"
    # 	exit
	# fi

	if [ -z "${params["host"]}" ]; then
		echo "exit 2"
		exit
	fi

	# echo "step 3"

	bw list items --session $TOKEN > /dev/null 2>&1

	if [ $? -ne 0 ]; then
		if [ -z "$bwuser" ]; then
			read -p "Bitwarden username: " bwuser < /dev/tty > /dev/tty
		fi

		if [ -z "$bwuser" ]; then
			exit
		fi

		bw login $bwuser > /dev/null

		if [ $? -ne 0 ]; then
			echo "Failed to login to Bitwarden" > /dev/stderr
			exit
		fi
	fi

	# echo "step 4"

  # TODO: us fx instead of jq, then remove jq from brewfile as well
	user=`bw list items --url ${params["host"]} --session ${TOKEN} | jq -r '.[0].login.username'`
	pass=`bw list items --url ${params["host"]} --session ${TOKEN}| jq -r '.[0].login.password'`

	if [ "x$user" == "x" ] || [ "x$pass" == "x" ]; then
		echo "Couldn't find host [${params["host"]}] in Bitwarden DB." > /dev/stderr
		exit
	fi

	echo username=$user
	echo password=$pass
fi
