#!/bin/zsh

# Uninstall script

# Ask for the administrator password upfront
sudo -v

# Keep sudo session persistent
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


# TODO: make option: default pick list of uninstallable apps/packages etc...
# other option - revert to new state

# TODO: revert all settings... make it shiny and new again ;)

# TODO: https://apple.stackexchange.com/questions/198623/uninstall-all-programs-installed-by-homebrew
# Uninstall Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"


# https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f
