#!/bin/zsh

# Update script

# Ask for the administrator password upfront
sudo -v

# Keep sudo session persistent
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &



# Check for macOS updates
sudo softwareupdate -i -a --restart



# TODO: present interactive lists of updateable software via all software managers


# # Upgrade any already-installed formulae.
# brew upgrade


# Update Homebrew itself
brew update

brew bundle cleanup

# Install and upgrade Homebrew packages
brew bundle

brew cu
# https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f
