#!/bin/zsh

# Update script

# Ask for the administrator password upfront
sudo -v

# Keep sudo session persistent
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &



# Check for macOS updates
sudo softwareupdate -i -a --restart

# https://scott-bollinger.com/macos-update-aio-alias

# TODO: present interactive lists of updateable software via all software managers


# # Upgrade any already-installed formulae.
# brew upgrade


# https://github.com/Homebrew/homebrew-autoupdate

# Update Homebrew itself
brew update

# brew bundle cleanup

# Cleaning up to match brewfile
# If you want your current system configuration to match your brewfile

# brew bundle --force cleanup

# Install and upgrade Homebrew packages
brew bundle

brew cu
# https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f
